# Generated by Django 6.0.3 on 2026-04-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
                ('next_steps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField()),
                ('rainfall', models.FloatField(default=0.0)),
                ('cloud_cover', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
