"""
Django settings for StormSense project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# it knows where my manage.py is
BASE_DIR = Path(__file__).resolve().parent.parent   


# helpful in all the production and debugging 
SECRET_KEY = 'django-insecure-t2_!%#)1e&c$2)%h=kp0z1_ch_cef)x$1$)pbcd9cmyr&4m##_'

# we turn this False when we deploy our project
DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'StormSense',
]


# it manages how security requests are handled
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# this tell the django how to route any URL
ROOT_URLCONF = 'StormSense.urls'


# hold the HTML templates and how to route them, how will they transition
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# it handles how our server works...all the settings of the server
WSGI_APPLICATION = 'StormSense.wsgi.application'


# maps the database from the frontend to backend
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# just validates that the passwords are good and according to the rules 
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# holds the space like where do we store or HTML, CSS, Js files
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',   # FIXED
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
